### ISSUE TITLE
.mdns-hosts not found 

### ISSUE THREAD

**Issue by aminekun90** [Richie765/mdns-listener#1]
I tried to run this project but it throws an error I'm on windows by the way -- and how do I do the configuration step on my machine -- : 
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\xxxx\repos\mdns-listener\undefined\.mdns-hosts'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (C:\Users\Amine Bouzahar\repos\mdns-listener\mdns-listener.js:19:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
```

**Comment by aminekun90** [comment]
Ok so i've created the file inside the project directory and edited this line 
```
const mdns_hosts = ".mdns-hosts";
```
it's working now !

**Comment by Richie765** [comment]
I have only tested it so far with macOS, so it is good to see that with this small change it also works on Windows! Thanks for trying out this tool.

**Comment by aminekun90** [comment]
Hi @Richie765, I've developed an npm package using your code you can find it here I've Added a credit to you thanks for everything : https://www.npmjs.com/package/mdns-listener-advanced and also updated the dependency to the latest version and tested it
